# Generated by Django 4.2.10 on 2024-05-25 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cosplay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cosplay_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CosPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cosplay_task", models.CharField(max_length=200)),
                ("due_date", models.DateField()),
                ("cosplay_notes", models.TextField(blank=True)),
                (
                    "cosplay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosplans.cosplay",
                    ),
                ),
                (
                    "cosplayer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
                "unique_together": {("cosplayer", "cosplay_task")},
            },
        ),
    ]
