# Generated by Django 4.2.10 on 2024-06-14 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cosplans", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cosplan",
            old_name="cosplay_notes",
            new_name="cosplan_details",
        ),
        migrations.RenameField(
            model_name="cosplan",
            old_name="cosplay_task",
            new_name="cosplan_task",
        ),
        migrations.AlterUniqueTogether(
            name="cosplan",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cosplay",
            name="cosplayer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="cosplan",
            name="cosplayer",
        ),
    ]
