# Generated by Django 4.2.10 on 2024-06-17 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cosplans", "0002_rename_cosplay_notes_cosplan_cosplan_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cosplan",
            name="cosplayer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cosplan",
            name="cosplay",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Cosplay",
        ),
    ]
