# Generated by Django 4.2.10 on 2024-05-27 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cosexpenses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cosexpense",
            name="cosplay",
        ),
        migrations.AddField(
            model_name="cosexpense",
            name="cosplayer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
