# Generated by Django 4.2.10 on 2024-06-20 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cosplans", "0001_initial"),
        ("cosexpenses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cosexpense",
            name="cosplay_name",
        ),
        migrations.AddField(
            model_name="cosexpense",
            name="cosplan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cosplans.cosplan",
            ),
        ),
    ]
