# Generated by Django 4.2.10 on 2024-06-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="fave_cosplay",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="next_convention",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
