# Generated by Django 4.2.10 on 2024-05-25 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cosplay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cosplay_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CosPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cosplay_task", models.CharField(max_length=200)),
                ("due_date", models.DateField()),
                ("cosplay_notes", models.TextField()),
                (
                    "cosplay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profiles.cosplay",
                    ),
                ),
            ],
            options={
                "unique_together": {("cosplay", "cosplay_task")},
            },
        ),
    ]
