# Generated by Django 4.2.10 on 2024-05-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0003_alter_userprofile_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CosPlan",
        ),
        migrations.DeleteModel(
            name="Cosplay",
        ),
    ]
